### ISSUE TITLE
Security issue 

### ISSUE THREAD

**Issue by nazihkalo** [dyte-in/docs#118]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Are you sure this is not an issue in Docusaurus?

- [X] It is not a Docusaurus issue

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

@vaibhavshn check twitter DMs

**Comment by vaibhavshn** [comment]
Hey, thank you for reaching out!
We’ve resolved the issue in DM.
