### ISSUE TITLE
[FIX] - Auto Collapsible Sidebar

### ISSUE THREAD

**Issue by himanshu-03** [dyte-in/docs#214]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

| Use case | Description |
| :--- | :--- |
| Overwhelming Navigation | The vast array of categories shown in the sidebar may be too much for new website visitors to handle. It is preferable to have the sidebar open for the sole category in which the user is interested |
| Scrolling Fatigue | If there are numerous categories in the sidebar, users may need to scroll extensively to find the specific category or content they are interested in, leading to scrolling fatigue. |
| Lack of Personalization | Users may want to customize their navigation experience by collapsing or prioritizing certain categories, which is not possible with a fixed sidebar |

### Proposed solution (optional)

Modifying the Docusaurus configuration file (typically docusaurus.config.js) to enable the collapsible sidebar feature will help us in solving this issue. It can be achieved by adjusting settings related to the sidebar in the configuration.

| Present Scenario | Post Scenario (Proposed Solution) |
| :-- | :-- |
| <img src="https://github.com/dyte-in/docs/assets/97957777/8f16ab42-88fc-4e8a-9c43-f885a68cfdae" width=200> | <img src="https://github.com/dyte-in/docs/assets/97957777/65e99d7d-178f-49f3-82cf-9582866c3dd4" width=200> |
| Currently, when I click on the `Build your own UI` category, it expands to reveal its subcategories. However, if I then want to navigate to the `Customizations` category, and I click on it, the sidebar for the `Build your own UI` category remains open and doesn't collapse automatically. This can make it confusing to navigate the sidebar efficiently. | In the improved scenario, when I click on the `Build your own UI` category, it will expand to reveal its subcategories just like before. However, if I then want to navigate to the `Customizations` category and click on it, the sidebar for the `Build your own UI` category will automatically collapse. This enhancement will make navigation more intuitive and efficient. |

**Comment by himanshu-03** [comment]
I would like to fix this issue!

**Comment by roerohan** [comment]
@vaibhavshn please take a call regarding this issue

**Comment by vaibhavshn** [comment]
Sure, PRs are always welcome!

**Comment by himanshu-03** [comment]
Hey @vaibhavshn just had a doubt!
Will this be counted towards hacktoberfest-2023 contributions?

**Comment by vaibhavshn** [comment]
> Will this be counted towards hacktoberfest-2023 contributions?

It should, but I am not completely sure. @Frenzyritz13 can tell for sure.
