### ISSUE TITLE
In-app Documentation link is not working

### ISSUE THREAD

**Issue by iprithvitharun** [dyte-in/docs#55]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Are you sure this is not an issue in Docusaurus?

- [X] It is not a Docusaurus issue

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

The "Documentation" CTA link in the app dashboard is broken. It points to `docs.dyte.in/docs` and not redirecting to `docs.dyte.io/docs/home/introduction`

<img width="532" alt="Screenshot 2022-06-14 at 5 14 24 PM" src="https://user-images.githubusercontent.com/58725708/173569607-0679878a-ee2e-4598-918f-0e6698f63ba7.png">

**Comment by roerohan** [comment]
Hey @iprithvitharun, taking a look into this. Will comment on this PR once it's fixed 👍

**Comment by roerohan** [comment]
Hey @iprithvitharun, it should be working now. Thanks for reporting this bug! Please re-open this issue if you face it again.
