### ISSUE TITLE
The active element in header is misconfigured

### ISSUE THREAD

**Issue by galanteria01** [dyte-in/docs#58]
### Are you certain it's a bug?

- [x] Yes, it looks like a bug

### Are you sure this is not an issue in Docusaurus?

- [X] It is not a Docusaurus issue

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

While we are at web sdk documentation the header has two selected element shown that are Web Sdk and Mobile Sdk both gets the class text-primary-100 so they looks like they are the active currently. 
[![Screenshot-2022-06-23-151852.png](https://i.postimg.cc/Wp5PDmYd/Screenshot-2022-06-23-151852.png)](https://postimg.cc/K43WwT2b)
```
<div class="hidden space-x-6 text-text-100 lg:flex">
<a class="inline-flex items-center text-sm font-medium hover:no-underline text-text-100" href="/react/quickstart">
Prebuilt SDKs
<span class="pill pill-warning ml-2">
OLD
</span>
</a>
<a class="inline-flex items-center text-sm font-medium hover:no-underline text-primary-100" href="/react-ui-kit/installation">
Web SDKs
<span class="pill ml-2">NEW</span>
</a><a class="inline-flex items-center text-sm font-medium hover:no-underline text-primary-100" href="/react-native-core/installation">
Mobile SDKs
<span class="pill ml-2">
NEW
</span>
</a>
<a href="/api/" class="text-sm font-medium hover:no-underline text-text-100">
API Reference
</a>
<a class="text-sm font-medium hover:no-underline text-text-100" href="/guides/integrating-with-webhooks">
Guides
</a>
</div>
```

While selecting the mobile sdk documentation the class is not assigned to any of the header elements and it remains to text-text-100 for all the elements respectively.

[![Screenshot-2022-06-23-151907.png](https://i.postimg.cc/DwFDB8M9/Screenshot-2022-06-23-151907.png)](https://postimg.cc/HVZBLsHz)

```
<div class="hidden space-x-6 text-text-100 lg:flex"><a class="inline-flex items-center text-sm font-medium hover:no-underline text-text-100" href="/react/quickstart">
Prebuilt SDKs
<span class="pill pill-warning ml-2">OLD</span>
</a>
<a class="inline-flex items-center text-sm font-medium hover:no-underline text-text-100" href="/react-ui-kit/installation">
Web SDKs
<span class="pill ml-2">
NEW
</span>
</a>
<a class="inline-flex items-center text-sm font-medium hover:no-underline text-text-100" href="/react-native-core/installation">
Mobile SDKs
<span class="pill ml-2">
NEW
</span>
</a>
<a href="/api/" class="text-sm font-medium hover:no-underline text-text-100">
API Reference
</a>
<a class="text-sm font-medium hover:no-underline text-text-100" href="/guides/integrating-with-webhooks">
Guides
</a>
</div>
```

**Comment by vaibhavshn** [comment]
Merged the linked PR. Closing this.

Thanks for contributing!
