### ISSUE TITLE
Update openAPI spec automatically

### ISSUE THREAD

**Issue by kushagra12** [dyte-in/docs#6]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

Currently there is an open API spec maintained in our backend repo but it's not the same shown to the clients. After the spec is merged to master, we have to manually update the spec file here.

### Proposed solution (optional)

Either use the deployte bot or a GitHub action to detect when the spec is updated on the backend and create a PR here automatically.

**Comment by alias-rahil** [comment]
I have added a workflow to keep the api-specs in the private fork of docs in sync with the api-specs in the backend repo. We can then selectively merge those changes here manually. We can close this now.
